Zarf (#8)
* Refactor code and remove unnecessary functions

* Relocate Docker files and update paths

The Docker files have been moved to the 'zarf/docker' directory. This relocation resulted in the adjustment of paths in the Dockerfile and Taskfile.yml. Furthermore, references to docker-compose in Taskfile.yml have been updated to point to the relocated docker-compose.yml. Lastly, golines linting command has been added to Taskfile.yml.

* Add Kubernetes configuration for Tawny service

This includes namespace, configmap, service, and deployment files for Tawny's API and Web servers. These files are placed under `zarf/k8s/tawny/`. Also adjusted Docker Compose and entrypoint files under `zarf/docker/` and created default values for a Postgres Helm chart.

* Refactor installation script and improve admin user handling

The installation script was refactored to remove Docker dependencies and introduce Helm for easier management. The handling of the admin user in the service initialization was changed to provide warnings instead of fatal errors when the admin user does not exist. This is to provide more flexibility and avoid crashes due to missing admin user. Notably, dependencies on Docker have been removed in favor of Kubernetes and Helm for application deployment.

* Update installation scripts to improve customizability

Made several changes to the installation scripts to allow easier customization. Specifically, exports used in the install script have been removed for better flexibility, allowing users to define their own OWNER and REPO. Helm command has been updated to handle upgrades, and helpful tools have been added to the arkade installation. The K8s location URLs were updated to be more flexible and namespaced the secret to match the repo. Also added name override option in postgres values yaml.

* Update Dockerfile path in GitHub workflow

The path to the Dockerfile in the GitHub workflow has been updated. Previously, it was not pointing to the correct location. Now it correctly points to the Dockerfile in the ./zarf/docker/ directory.

* update command

* Fix broken secret creation

* Change command to use entrypoint so that migrations run

* Update host references and add backup for etc/hosts

The commit introduces a function to backup the original /etc/hosts file before making changes. It also updates the host references in the ingress.yaml file. This is aimed to ensure smoother transition and minimize any potential conflicts with existing settings.

* Update docker build in CI

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -1,8 +1,9 @@
 #!/bin/bash
 set -e -x -o pipefail
 
-export OWNER="danielmichaels"
-export REPO="tawny"
+ADMIN_PASSWORD="${ADMIN_PASSWORD}"
+OWNER="danielmichaels"
+REPO="tawny"
 export ARKADE=/usr/local/bin/arkade
 # When running as a startup script (cloud-init), the HOME variable is not always set.
 # As it is required for arkade to properly download tools,
@@ -12,24 +13,18 @@ if [ -z "${HOME}" ]; then
 fi
 
 K3S_VERSION="v1.29.3+k3s1"
-DOCKER_VERSION="24.0"
-TAWNY_DOMAIN="${TAWNY_DOMAIN:-}"
-TAWNY_PORT="${TAWNY_PORT:-9090}"
-# Used in docker-compose
-LATEST_RELEASE="${VERSION:-latest}"
-export LATEST_RELEASE
-
-echo "Finding latest version from GitHub"
-VERSION=$(curl -sI https://github.com/$OWNER/$REPO/releases/latest | grep -i "location:" | awk -F"/" '{ printf "%s", $NF }' | tr -d '\r')
+echo "Finding version from GitHub"
+RELEASE_VERSION=$(curl -sI https://github.com/$OWNER/$REPO/releases/latest | grep -i "location:" | awk -F"/" '{ printf "%s", $NF }' | tr -d '\r')
+VERSION="${VERSION:-$RELEASE_VERSION}"
 echo "$VERSION"
 
 if [ ! "$VERSION" ]; then
-  echo "Failed while attempting to get latest version"
+  echo "Failed while attempting to get version"
   exit 1
 fi
 
-if [ ! "$TAWNY_DOMAIN" ]; then
-  echo "No Domain set; Caddy defaulting to port 80"
+if [ ! "$ADMIN_PASSWORD" ]; then
+  ADMIN_PASSWORD=$(openssl rand -base64 14)
 fi
 
 SUDO=sudo
@@ -72,6 +67,7 @@ install_required_packages() {
 install_arkade() {
   curl -sLS https://get.arkade.dev | $SUDO sh
   arkade --help
+  arkade get helm k9s kubectx kubens
   add_arkade_to_bash
 }
 
@@ -81,84 +77,53 @@ add_arkade_to_bash() {
 
 install_k3s() {
   echo "Installing k3s $K3S_VERSION"
-  curl -sfL https://get.k3s.io | \
-  K3S_KUBECONFIG_MODE="644" \
-  INSTALL_K3S_EXEC="--disable traefik" \
-  sh -
+  curl -sfL https://get.k3s.io |
+    K3S_KUBECONFIG_MODE="644" \
+      INSTALL_K3S_EXEC="--disable traefik" \
+      sh -
   export KUBECONFIG="/etc/rancher/k3s/k3s.yaml"
   arkade install traefik2 --dashboard --wait
   arkade install cert-manager --wait
-}
-
-is_docker_snap() {
-  # Detect if docker is installed via snap
-  if [ -x "$(command -v snap)" ]; then
-    if snap list | grep -q docker; then
-      echo "Docker is installed via snap."
-      echo "Please remove Docker with snap (snap remove docker) and execute this script."
-      echo "Docker in snap will result in odd behaviour from the application and cannot be used."
-      exit 1
-    fi
-  fi
-}
-
-install_docker() {
-  # exit early if docker is snap installed
-  is_docker_snap
-  # automated script
-  if ! [ -x "$(command -v docker)" ]; then
-    echo "Docker is not installed. Installing Docker."
-    curl https://releases.rancher.com/install-docker/${DOCKER_VERSION}.sh | sh
-    if [ -x "$(command -v docker)" ]; then
-      echo "Docker installed successfully."
-    else
-      echo "Docker installation failed with Rancher script. Trying with official script."
-      curl https://get.docker.com | sh -s -- --version ${DOCKER_VERSION}
-      if [ -x "$(command -v docker)" ]; then
-        echo "Docker installed successfully."
-      else
-        echo "Docker installation failed with official script."
-        echo "Maybe your OS is not supported?"
-        echo "Please visit https://docs.docker.com/engine/install/ and install Docker manually to continue."
-        exit 1
-      fi
-    fi
-  fi
-  enable_docker_ip_forwarding
-}
-
-non_root_docker() {
-  $SUDO usermod -aG docker "$USER"
-  newgrp docker
-}
-
-enable_docker_ip_forwarding() {
-  $SUDO /sbin/sysctl -w net.ipv4.conf.all.forwarding=1
-  echo "net.ipv4.conf.all.forwarding=1" | $SUDO tee -a /etc/sysctl.conf
 }
 
 make_directories() {
   $SUDO mkdir -p /var/tawny/{source,data}
 }
 
+etc_hosts() {
+  $SUDO cp /etc/hosts /etc/hosts.bak
+  echo "127.0.0.1 api.tawny.internal tawny.internal" >> /etc/hosts
+}
+
 install_tawny() {
-  $SUDO curl -sfL https://raw.githubusercontent.com/danielmichaels/tawny/main/docker-compose.yml \
-        -o /var/tawny/source/docker-compose.yml
-  $SUDO docker compose -f /var/tawny/source/docker-compose.yml up \
-        --pull always --remove-orphans --force-recreate --detach
+  echo "download manifests"
+  kubectl apply -f "https://raw.githubusercontent.com/$OWNER/$REPO/$VERSION/zarf/k8s/namespace.yaml" || true
+  helm upgrade --install postgres oci://registry-1.docker.io/bitnamicharts/postgresql \
+    --namespace tawny \
+    --values "https://raw.githubusercontent.com/$OWNER/$REPO/$VERSION/zarf/k8s/postgres/values.yaml" || true
+  # add a wait for
+  kubectl create secret generic admin-password --from-literal="admin-password=${ADMIN_PASSWORD}" --namespace $REPO || true
+
+  manifests=("configmap" "deployment" "ingress" "service")
+
+  for manifest in "${manifests[@]}"; do
+    kubectl apply -f "https://raw.githubusercontent.com/$OWNER/$REPO/$VERSION/zarf/k8s/$REPO/$manifest.yaml"
+  done
 }
 
 printer() {
   echo -e "\nCongratulations! Your Tawny instance is ready to use.\n"
-  echo "Please visit http://$(curl -4s https://ifconfig.io):9090 to get started."
+  echo -e "Please visit http://$(curl -4s https://ifconfig.io):9090 to get started.\n"
+  echo "Login with:"
+  echo "Username: admin"
+  echo "Password: $ADMIN_PASSWORD"
+  echo "Consider changing this after first login"
 }
 
 install_required_packages
 install_arkade
 install_k3s
-install_docker
 make_directories
 install_tawny
+etc_hosts
 printer
-# must come last as it exits the script
-non_root_docker
